Traceback (most recent call last):
  File "archi_v3_18.py", line 99, in <module>
    history = model.fit(train_x, train_y, epochs=50, validation_split=0.1, callbacks=list_cb)
  File "C:\Users\antoi\anaconda3\envs\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\antoi\anaconda3\envs\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\antoi\anaconda3\envs\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\antoi\anaconda3\envs\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "C:\Users\antoi\anaconda3\envs\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\antoi\anaconda3\envs\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 560, in call
    ctx=ctx)
  File "C:\Users\antoi\anaconda3\envs\Python37\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
KeyboardInterrupt
